name: Credit Card Validator Action

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: .
      with:
        args: test
    - name: Build Docker image
      run: docker build -t creditcard/image .
    - name: Run Docker image
      run: docker run --rm -p 8080:8080 -v "`pwd`/../src:/src" -v "`pwd`/../data:/data" -w /src docker.io/creditcard/image

