name: Credit Card Validator Action

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t creditcard/image .

